website/auth.py
import MySQLdb.cursors
from website import create_app
from flask import Blueprint, render_template, request, url_for, redirect, session, flash
from flask_mysqldb import MySQL
import bcrypt
import cv2
import os
from werkzeug.exceptions import abort

nomImOr = ""
nomImMod = ""

APP_ROOT = os.path.dirname(os.path.abspath(__file__))
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

auth = Blueprint('auth', __name__)

app = create_app()

mysql = MySQL(app)


def get_post(post_id):
    cur = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
    cur.execute("SELECT * FROM posts WHERE id = %s", (post_id,))
    new_post = cur.fetchone()
    print(new_post)
    cur.close()
    if post is None:
        abort(404)
    return post


def get_customer_id(email):
    cur = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
    cur.execute("SELECT * FROM Customer WHERE email=%s", (email,))
    user = cur.fetchone()
    customer_id = user['id']
    cur.close()
    if customer_id is None:
        abort(404)
    return customer_id


def process_img(img):
    imgmod = img
    imgmod[imgmod < 128] = 0
    return imgmod


@auth.route('/delete')
def delete_img():
    target = os.path.join(APP_ROOT, 'static')
    destination = "\\".join([target, nomImOr])
    destination_modif = "\\".join([target, nomImMod])
    os.remove(destination)
    os.remove(destination_modif)
    return render_template('upload.html', nomimageOr=nomImOr, nomimagemodif=nomImMod)


@auth.route('/sign_in', methods=['GET', 'POST'])
def sign_in():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password'].encode('utf-8')

        cur = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
        cur.execute("SELECT * FROM Customer WHERE email=%s", (email,))
        user = cur.fetchone()
        cur.close()

        if user is None:
            return render_template("sign_in.html", error="Incorrect E-mail !")
        else:
            if bcrypt.hashpw(password, user['password'].encode('utf-8')) == user['password'].encode('utf-8'):
                session['first_name'] = user['first_name']
                session['email'] = user['email']
                return render_template("home.html")
            else:
                return render_template("sign_in.html", error="Incorrect password !")
    else:
        return render_template("sign_in.html")


@auth.route('/sign_out')
def sign_out():
    session.clear()
    return render_template("home.html")


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    cursor = mysql.connection.cursor()
    query = "SELECT * FROM gender"
    cursor.execute(query)
    gender = cursor.fetchall()
    query = "SELECT * FROM specialization"
    cursor.execute(query)
    specialization = cursor.fetchall()
    query = "SELECT * FROM organization_type"
    cursor.execute(query)
    organization_type = cursor.fetchall()
    query = "SELECT * FROM pm_system"
    cursor.execute(query)
    pm_system = cursor.fetchall()
    if request.method == 'POST':
        first_name = request.form['first_name']
        last_name = request.form['last_name']
        gender = request.form['gender']
        email = request.form['email']
        password = request.form['password'].encode('utf-8')
        organization = request.form['organization']
        specialization = request.form['specialization']
        organization_type = request.form['organization_type']
        pm_system = request.form['pm_system']

        hashed = bcrypt.hashpw(password, bcrypt.gensalt(12))

        params = [email]

        cur = mysql.connection.cursor()

        count = cur.execute("SELECT * FROM customer WHERE email=%s", (params))

        if count == 0:
            cur.execute(
                "INSERT INTO Customer (first_name, last_name, gender_id, email, password, organization, specialization_id, organization_type_id, pm_system_id) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)",
                (first_name, last_name, gender, email, hashed, organization, specialization, organization_type,pm_system,))

            mysql.connection.commit()
            session['first_name'] = first_name
            session['email'] = email

            return redirect(url_for("views.home"))

        else:
            query = "SELECT * FROM gender"
            cursor.execute(query)
            gender = cursor.fetchall()
            query = "SELECT * FROM specialization"
            cursor.execute(query)
            specialization = cursor.fetchall()
            query = "SELECT * FROM organization_type"
            cursor.execute(query)
            organization_type = cursor.fetchall()
            query = "SELECT * FROM pm_system"
            cursor.execute(query)
            pm_system = cursor.fetchall()
            return render_template("sign_up.html", error="E-mail already exist !", gender=gender, specialization=specialization, organization_type=organization_type, pm_system=pm_system)

    return render_template("sign_up.html", gender=gender, specialization=specialization, organization_type=organization_type, pm_system=pm_system)


@auth.route('/post')
def index():
    customer_id = get_customer_id(session['email'])
    cur = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
    cur.execute('SELECT * FROM posts WHERE Customer_id = %s', (customer_id,))
    posts = cur.fetchall()
    cur.close()
    print(posts)
    return render_template('FlaskBlog.html', posts=posts)


@auth.route('/<int:post_id>')
def post(post_id):
    post = get_post(post_id)
    return render_template('post.html', post=post)


@auth.route('/upload')
def upload():
    return render_template('upload.html')


@auth.route('/traitement')
def traitement():
    target = os.path.join(APP_ROOT, 'static')
    destination = "\\".join([target, nomImOr])
    customer_id = get_customer_id(session['email'])
    cur = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
    cur.execute('INSERT INTO x_ray (link, customer_id) VALUES ( %s, %s);', (destination, customer_id,))
    x_ray_id = cur.lastrowid
    destination_modif = "\\".join([target, nomImMod])
    cur.execute('INSERT INTO x_ray_segmentation (link, x_ray_id) VALUES ( %s, %s)', (destination_modif, x_ray_id,))
    mysql.connection.commit()
    cur.close()
    return render_template('traitement_image.html', nomimageOr=nomImOr, nomimagemodif=nomImMod)


@auth.route('/upload', methods=['GET', 'POST'])
def upload_file():
    target = os.path.join(APP_ROOT, 'static')
    print(target)
    if not os.path.isdir(target):
        os.mkdir(target)
    else:
        print("Couldn't create upload directory: {}".format(target))
    print(request.files.getlist("file"))
    if request.method == 'POST':
        # Récupération du nom du fichier :
        f = request.files['file']
        if f.filename == '':
            return render_template('upload.html', error="Choose a file before upload !")
        elif f.filename.split('.')[1] not in ALLOWED_EXTENSIONS:
            return render_template('upload.html', error="Extension not supported !")
        else:
            destination = "\\".join([target, f.filename])
            print("\n\t" + destination + "\n")
            f.save(destination)

            # Lecture de l'image :
            imageNG = cv2.imread(destination, 0)
            print(imageNG.shape)

            # Traitement de l'image :
            mod = process_img(imageNG)

            # Sauvegarde :
            var = os.path.splitext(f.filename)
            nomimagemodif = var[0] + "_modif" + var[1]
            print("mod : " + nomimagemodif)
            cv2.imwrite("website/static/" + nomimagemodif, mod)

            global nomImOr
            global nomImMod
            nomImOr = f.filename
            nomImMod = nomimagemodif

            # return 'file uploaded successfully'
            return render_template('affichage_image.html', nomimageOr=nomImOr, nomimagemodif=nomImMod)


@auth.route('/create', methods=('GET', 'POST'))
def create():
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']
        if not title:
            flash('Title is required!')
        else:
            cur = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
            cur.execute('INSERT INTO posts ( title, content, customer_id) VALUES ( %s, %s, %s)',
                         (title, content, get_customer_id(session['email'],)))
            cur.close()
            return redirect(url_for('auth.index'))

    return render_template('create.html')


@auth.route('/<int:id>/edit', methods=('GET', 'POST'))
def edit(id):
    post = get_post(id)
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']

        if not title:
            flash('Title is required!')
        else:
            cur = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
            cur.execute('UPDATE posts SET title = %s, content = %s WHERE id = %s',
                         (title, content, id))
            cur.commit()
            cur.close()
            return redirect(url_for('index'))

    return render_template('edit.html', post=post)


@auth.route('/<int:id>/delete', methods=('POST',))
def delete(id):
    post = get_post(id)
    cur = mysql.connection.cursor(MySQLdb.cursors.DictCursor)
    cur.execute('DELETE FROM posts WHERE id = %s', (id,))
    cur.commit()
    cur.close()
    flash('"{}" was successfully deleted!'.format(post['title']))
    return redirect(url_for('index'))

website/templates/FlaskBlog.html
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} Welcome to FlaskBlog {% endblock %}</h1>
    {% for post in posts %}
            <h2>{{ post['title'] }}</h2>
        </a>
        <span class="badge badge-primary">{{ post['created'] }}</span>
        <a href="{{ url_for('auth.edit', id=post['id']) }}">
            <span class="badge badge-warning">Edit</span>
        </a>
        <hr>
    {% endfor %}
{% endblock %}

website/templates/affichage_image.html
{% extends 'base.html' %}

{% block content %}
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='style.css') }}">
</head>
<body>
<div class="images">
    <div class="image-upload">
        <h2>Image uploadée.</h2>
        <img src="{{url_for('static', filename=nomimageOr)}} " alt="Image de base">
    </div>
</div>
</body>
<footer>
    <p>Êtes vous sûr de vouloir mettre cette image ?</p>
    <div class="footer-button">
        <button type="button" class="margin-right" onclick="window.location.href='{{ url_for('auth.delete_img') }}';">Non</button>
        <button type="button" onclick="location.href='traitement';">Oui</button>
    </div>
</footer>
</html>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename= 'css/style.css') }}">
    <title>{% block title %}Home{% endblock %}</title>
</head>
<header>
    <input type="checkbox" id="nav-toggle" class="nav-toggle">
    <nav>
        <div class="big-circle">
            <img class="big-logo" src="{{ url_for('static', filename= 'img/logo.png') }}">
        </div>
        <ul>
            <li><a href="#">Back to Artefakt-AI</a></li>
            {% if session['first_name'] %}
            <li><a href="{{url_for('auth.upload')}}">Upload</a></li>
            <li><a href="/post">Posts</a></li>
            <li><a href="{{url_for('auth.create')}}">New Posts</a></li>
            <li><a href="/sign_out">Sign-Out</a></li>
            {% else %}
            <li><a href="/">Home</a></li>
            <li><a href="/sign-up">Sign-Up</a></li>
            <li><a href="/sign_in">Sign-In</a></li>
            {% endif %}
        </ul>
    </nav>
    <label for="nav-toggle" class="nav-toggle-label">
        <span></span>
    </label>
</header>
<body>
<div class="container_small">
    <div class="small-circle">
        <img class="logo" src="{{ url_for('static', filename= 'img/logo.png') }}">
    </div>
</div>
{% block content %}
{% endblock %}
</body>
</html>

website/templates/create.html
{% extends 'base.html' %}

{% block content %}
<h1>{% block title %} Create a New Post {% endblock %}</h1>

<form method="post">
    <div class="form-group">
        <label for="title" >Title</label>
        <input type="text" name="title"
               placeholder="Post title" class="form-control"
               value="{{ request.form['title'] }}"></input>
    </div>

    <div class="form-group">
        <label for="content" >Content</label>
        <textarea name="content" placeholder="Post content"
                  class="form-control">{{ request.form['content'] }}</textarea>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>
{% endblock %}

website/templates/edit.html
{% extends 'base.html' %}

{% block content %}
<h1>{% block title %} Edit "{{ post['title'] }}" {% endblock %}</h1>
<form method="post">
    <div class="form-group">
        <label for="title">Title</label>
        <input type="text" name="title" placeholder="Post title"
               class="form-control"
               value="{{ request.form['title'] or post['title'] }}">
    </div>

    <div class="form-group">
        <label for="content">Content</label>
        <textarea name="content" placeholder="Post content"
                  class="form-control">{{ request.form['content'] or post['content'] }}</textarea>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>
<hr>

<form action="{{ url_for('auth.delete', id=post['id']) }}" method="POST">
    <input type="submit" value="Delete Post"
            class="btn btn-danger btn-sm"
            onclick="return confirm('Are you sure you want to delete this post?')">
</form>

{% endblock %}

website/templates/home.html
{% extends "base.html" %}

{% block title %}
Home
{% endblock %}

{% block content %}
{% endblock %}

website/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>{% block title %} Welcome to FlaskBlog {% endblock %}</h1>
{% endblock %}

website/templates/post.html
{% extends 'base.html' %}

{% block content %}
    <h2>{% block title %} {{ post['title'] }} {% endblock %}</h2>
    <span class="badge badge-primary">{{ post['created'] }}</span>
    <p>{{ post['content'] }}</p>
{% endblock %}

website/templates/sign_in.html
{% extends "base.html" %}

{% block title %}
Sign-In
{% endblock %}

{% block content %}
<div class="body">
    {% if error %}
    <div class="error">
        <p>{{ error }}</p>
    </div>
    {% endif %}
    <div class="container">
        <div class="title">Sign-In</div>
        <form method="POST">
            <div class="user-details">
                <div class="input-box">
                    <span class="details">E-mail</span>
                    <input type="email" name="email" placeholder="Your e-mail" required>
                </div>
                <div class="input-box">
                    <span class="details">Password</span>
                    <input type="password" name="password" placeholder="Your password" required>
                </div>
            </div>
            <div class="button">
                <input type="submit" Value="Sign-In">
            </div>
        </form>
    </div>
</div>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}

{% block title %}
Sign Up
{% endblock %}

{% block content %}
<div class="body">
    {% if error %}
    <div class="error">
        <p>{{ error }}</p>
    </div>
    {% endif %}
    <div class="container">
        <div class="title">Sign-Up</div>
        <form action="#" method="POST">
            <div class="user-details">
                <div class="input-box">
                    <span class="details">First Name</span>
                    <input type="text" name="first_name" placeholder="Your name" required>
                </div>
                <div class="input-box">
                    <span class="details">Last Name</span>
                    <input type="text" name="last_name" placeholder="Last name" required>
                </div>
                <div class="input-box">
                    <span class="details">Gender</span>
                    <select name="gender" required>
                        {% for row in gender %}
                            <option value="{{row[0]}}">{{row[1]}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="input-box">
                    <span class="details">E-mail</span>
                    <input type="email" name="email" placeholder="Your e-mail" required>
                </div>
                <div class="input-box">
                    <span class="details">Password</span>
                    <input type="password" name="password" placeholder="Your password" required>
                </div>
                <div class="input-box">
                    <span class="details">Specialization</span>
                    <select name="specialization">
                        {% for row in specialization %}
                        <option value="{{row[0]}}">{{row[1]}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="input-box">
                    <span class="details">Organization type</span>
                    <select name="organization_type">
                        {% for row in organization_type %}
                            <option value="{{row[0]}}">{{row[1]}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="input-box">
                    <span class="details">Organization</span>
                    <input type="text" name="organization" placeholder="Name of your organization">
                </div>
                <div class="input-box">
                    <span class="details">Practice Management System</span>
                    <select name="pm_system">
                        {% for row in pm_system %}
                        <option value="{{row[0]}}">{{row[1]}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="button">
                <input type="submit" Value="Sign-Up">
            </div>
        </form>
    </div>
</div>
{% endblock %}

website/templates/super.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename= 'css/style.css') }}">
    <title>{% block title %}Home{% endblock %}</title>
</head>
<header>
    <input type="checkbox" id="nav-toggle" class="nav-toggle">
    <nav>
        <div class="big-circle">
            <img class="big-logo" src="{{ url_for('static', filename= 'img/logo.png') }}">
        </div>
        <ul>
            <li><a href="/">Home</a></li>
            {% if session['first_name'] %}
            <li><a href="/sign_out">Sign-Out</a></li>
            {% else %}
            <li><a href="/sign-up">Sign-Up</a></li>
            <li><a href="/sign_in">Sign-In</a></li>
            {% endif %}
            <li><a href="/post">Posts</a></li>
        </ul>
    </nav>
    <label for="nav-toggle" class="nav-toggle-label">
        <span></span>
    </label>
</header>
<body>
<div class="container_small">
    <div class="small-circle">
        <img class="logo" src="{{ url_for('static', filename= 'img/logo.png') }}">
    </div>
</div>
{% block content %}
{% endblock %}
</body>
</html>

website/templates/traitement_image.html
{% extends 'base.html' %}

{% block content %}
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='style.css') }}">
</head>
<body>
<div class="images">
    <div class="image-upload">
        <h2>Image uploadée.</h2>
        <img src="{{url_for('static', filename=nomimageOr)}}" alt="Image de base">
    </div>
    <div class="image-modif">
        <h2>Image modifiée.</h2>
        <img src="{{url_for('static', filename=nomimagemodif)}}" alt="Image modifiée">
    </div>
</div>
</body>
<footer>
    <p>Voulez vous essayer avec une nouvelle image ?</p>
    <div class="footer-button">
        <button type="button" class="margin-right" onclick="location.href='/';">Non</button>
        <button type="button" onclick="location.href='upload';">Oui</button>
    </div>
</footer>

</html>
{% endblock %}

website/templates/upload.html
{% extends 'base.html' %}

{% block content %}
<h1>{% block title %} Upload file {% endblock %}</h1>

<html>
<body>
<div class="body">
    {% if error %}
    <div class="error">
        <p>{{ error }}</p>
    </div>
    {% endif %}
    <div class="container">
        <form action="http://localhost:5000/upload" method="POST" enctype="multipart/form-data">
            <div class="upload">
                <input type="file" name="file" class="upload-box">
            </div>
            <div class="button">
                <input type="submit" Value="Upload">
            </div>
        </form>
    </div>
</div>
</body>
</html>
{% endblock %}